spring:
  thymeleaf:
    cash: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&charaterEncodeing=UTF-8&serverTime=Asia/Shanghai
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 3000
      connection-test-query: SELECT 1
    username: root
    password: 12345678
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.dz.seckill.pojo

logging:
  level:
    com.dz.seckill.mapper: DEBUG